version: '3.8'

services:
  sae-generator:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - HF_HOME=/data/hf_cache
      - TRANSFORMERS_CACHE=/data/hf_cache
      - MODEL_NAME=${MODEL_NAME:-gemma-2-9b}
      - SETTING=${SETTING:-normal}
      - DEVICE=${DEVICE:-cuda:0}
      - STORAGE_BACKEND=${STORAGE_BACKEND:-s3}
      - STORAGE_BUCKET=${STORAGE_BUCKET:-sae-probes-activations}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcs-key.json
    volumes:
      - ./data:/app/data
      - ./hf_cache:/data/hf_cache
      - ${GCS_KEY_PATH:-/dev/null}:/app/gcs-key.json:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["python", "cloud_deployment/run_cloud_generation.py"]